
services:
  litestar_server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - {{ secrets.TRAEFIK_NETWORK }}
    # ports:
    #   - 8000:8000 # handled by traefik
    restart: unless-stopped
    labels:
      # Main HTTPS router
      - traefik.enable=true
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}.rule=Host(`{{ secrets.MY_DOMAIN }}`)
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}.entrypoints=websecure
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}.tls.certresolver=myresolver
      - traefik.http.services.{{ secrets.ROOTSITE.USERNAME }}.loadbalancer.server.port={{ secrets.ROOTSITE.APPLICATION_PORT }}

      # HTTP router for redirecting to HTTPS
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}-http.rule=Host(`{{ secrets.MY_DOMAIN }}`)
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}-http.entrypoints=web
      - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}-http.middlewares=redirect-to-https

      # Middleware for redirecting HTTP to HTTPS
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # - traefik.http.routers.{{ secrets.ROOTSITE.USERNAME }}.middlewares=authelia@docker

networks:
  {{ secrets.TRAEFIK_NETWORK }}:
    external: true
